apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-integrator-service
  namespace: payplus-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-integrator-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gateway-integrator-service
    spec:
      containers:
      - name: gateway-integrator-service
        image: 975050277554.dkr.ecr.ap-south-1.amazonaws.com/payplus/gateway-integrator-service:1.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "768Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-integrator-service
  namespace: payplus-production
spec:
  selector:
    app: gateway-integrator-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
